refactor: rename "GUI tool" => "design tool", and "export tool" => "translation tool"
design-tokens/community-group pull request #156
Opened 2022-07-05 18:21 UTC by lauthieb

In order to be more consistent, I've proposed to align terms of "GUI tool" & "design tool". But also terms of "export tool" & "translation tool".

So, this PR is there to close my issue about this: closes #152

Btw, thanks a lot @c1rrus for your comment on this:

> Good point!
> 
> I think you're right, we've used multiple terms to mean the same thing and ought to clean that up.

Feel free if you want to challenge :)

Have a nice day,

2022-07-21 14:54 UTC, lauthieb commented
Hi @kaelig, hope you're well :)
What will be the next step for this proposal?
Thanks a lot!

2022-08-09 07:26 UTC, c1rrus requested changes
Apologies for the long delay before reviewing this (life got in the way).

Thank you so much for taking the time to clear up the "translation tool" / "export tool" inconsistencies! However, I think a few of the other changes should be reverted before this can be approved and merged.

2022-08-09 07:26 UTC, c1rrus commented on technical-reports/format/groups.md
> -- A GUI tool that lets users browse or select tokens could display this info alongside the corresponding group or as a tooltip
I would leave GUI as it is here. This advice applies to any tool that has a graphical user interface, regardless of whether it is a (UI) design tool or not.

2022-08-09 07:26 UTC, c1rrus commented on technical-reports/format/groups.md
> +### Design tools
Same comment as above. I'd prefer to keep this as "GUI tools" as this advice can apply to tools that are not design tools but still have a GUI.

2022-08-09 21:18 UTC, lauthieb reviewed
Hi @c1rrus, thanks a lot for your review!
Just reverted to "GUI tool" :)

2022-08-09 21:18 UTC, lauthieb commented on technical-reports/format/groups.md
> +### Design tools
```suggestion
### GUI tools
```

2022-08-09 21:18 UTC, lauthieb commented on technical-reports/format/groups.md
> +- A Design tool that lets users browse or select tokens could display this info alongside the corresponding group or as a tooltip
```suggestion
- A GUI tool that lets users browse or select tokens could display this info alongside the corresponding group or as a tooltip
```

2022-08-10 07:32 UTC, c1rrus approved these changes
Lovely! Thanks so much for making those amends!

2022-08-10 07:32 UTC, merged